const glossaryItems = [
  {
    term: "Input (Fresh)",
    description: "New input tokens that were not served from cache.",
  },
  {
    term: "Input (Total)",
    description: "Total input tokens across calls in the selected time window.",
  },
  {
    term: "Cache Read",
    description: "Tokens read from cache. These are usually cheaper than fresh input.",
  },
  {
    term: "Cache Creation / Cache Write",
    description: "Tokens used to write cache entries for later reuse.",
  },
  {
    term: "Output",
    description: "Tokens generated by the model.",
  },
  {
    term: "Calls",
    description: "Number of recorded LLM calls.",
  },
  {
    term: "Latency",
    description: "How long a call took from start to finish.",
  },
  {
    term: "TTFT",
    description: "Time To First Token, the delay before the first token is returned.",
  },
  {
    term: "Cost and Credits",
    description: "Estimated cost in USD and equivalent credits based on token usage.",
  },
];

const sections = [
  {
    title: "Getting Started",
    points: [
      "Open VS Code and use Copilot Chat as usual.",
      "The dashboard fills in when the app receives OTel data from Copilot.",
      "If no data appears, verify that github.copilot.chat.otel.enabled is set to true.",
    ],
  },
  {
    title: "Live Tab",
    points: [
      "Shows recent calls in near real-time through the live stream (green dot means connected).",
      "Filter by Agent and time window (5m, 1h, today, 24h, 7d, 30d).",
      "The table shows model, agent, tokens by category, and per-call cost.",
    ],
  },
  {
    title: "History Tab",
    points: [
      "Today: summary of current-day activity, cost/latency spikes, and detailed rows.",
      "Trends: development over time with selectable buckets (day, week, month, year).",
      "Insights: analysis of models, tool usage, cache impact, and forecasts.",
    ],
  },
  {
    title: "Interpretation Tips",
    points: [
      "High Cache Read with stable quality often indicates good reuse and lower cost.",
      "Many calls with high latency can indicate heavy context, network variability, or model choice.",
      "Compare Today with Trends to separate temporary spikes from persistent patterns.",
    ],
  },
];

export function CopilotHelp() {
  return (
    <main className="max-w-6xl mx-auto px-3 sm:px-6 py-6 space-y-6">
      <section className="rounded-xl border border-slate-800 bg-slate-900/40 p-4 sm:p-5">
        <h1 className="text-lg sm:text-xl font-semibold tracking-tight text-slate-100">
          Help: How to Read the Copilot Token Dashboard
        </h1>
        <p className="mt-2 text-sm text-slate-300 max-w-3xl leading-6">
          This page explains how the dashboard works, what the key metrics mean, and how to use each
          view to understand cost, token usage, and performance.
        </p>
      </section>

      <section className="grid gap-4 md:grid-cols-2">
        {sections.map((section) => (
          <article
            key={section.title}
            className="rounded-xl border border-slate-800 bg-slate-900/40 p-4 sm:p-5"
          >
            <h2 className="text-sm uppercase tracking-wider text-slate-400">{section.title}</h2>
            <ul className="mt-3 space-y-2 text-sm text-slate-200">
              {section.points.map((point) => (
                <li key={point} className="leading-6">
                  • {point}
                </li>
              ))}
            </ul>
          </article>
        ))}
      </section>

      <section className="rounded-xl border border-slate-800 bg-slate-900/40 p-4 sm:p-5">
        <h2 className="text-sm uppercase tracking-wider text-slate-400">Glossary</h2>
        <div className="mt-3 grid gap-3 sm:grid-cols-2">
          {glossaryItems.map((item) => (
            <article
              key={item.term}
              className="rounded-lg border border-slate-800 bg-slate-950/50 p-3"
            >
              <h3 className="text-sm font-semibold text-amber-200">{item.term}</h3>
              <p className="mt-1 text-sm text-slate-300 leading-6">{item.description}</p>
            </article>
          ))}
        </div>
      </section>
    </main>
  );
}
